this.pagejs=e=>{(()=>{"use strict";const t="vault"in e;if(t&&void 0===e.vault)throw"Invalid vault";const n=e.vault=e.vault||(e=>{const t=Object.call,n=t.bind(t),o=Object.assign,r=Object.getOwnPropertyDescriptor,s=e=>o({__proto__:null},e);return s({sourceWindow:e,cSO:s,F_c:n,F_a:Object.apply,F_b:Object.bind,F_tS:Function.toString,A_fE:[].forEach,A_so:[].some,A_sh:[].shift,A_j:[].join,A_iO:[].indexOf,A_iA:Array.isArray,O_a:o,O_k:Object.keys,O_v:Object.values,O_dP:Object.defineProperties,
O_dPy:Object.defineProperty,O_hOP:Object.hasOwnProperty,O_gOPN:Object.getOwnPropertyNames,O_gOPD:r,O_gOPDs:Object.getOwnPropertyDescriptors,O_gPO:Object.getPrototypeOf,O_tS:{}.toString,J_p:JSON.parse,J_s:JSON.stringify,M_f:Math.floor,M_r:Math.random,M_m:Math.max,M_mi:Math.min,M_i:MutationEvent.prototype.initMutationEvent,M_pA:MutationEvent.prototype.ADDITION,M_pAT:MutationEvent.AT_TARGET,N_tS:(0).toString,N_MSI:Number.MAX_SAFE_INTEGER,P_t:Promise.prototype.then,P_c:Promise.prototype.catch,
R_rABS:FileReader.prototype.readAsBinaryString,R_rAT:FileReader.prototype.readAsText,R_r:r(FileReader.prototype,"result").get,R_enq:e.ReadableStreamDefaultController?e.ReadableStreamDefaultController.prototype.enqueue:null,R_cl:e.ReadableStreamDefaultController?e.ReadableStreamDefaultController.prototype.close:null,S_fCC:String.fromCharCode,S_sl:"".slice,S_su:"".substr,S_sp_nr:"".split,S_iO:"".indexOf,S_tr:"".trim,S_r_nr:"".replace,S_rA_nr:"".replaceAll,S_cCA:"".charCodeAt,S_tLC:"".toLowerCase,
S_tUC:"".toUpperCase,Y_tST:Symbol.toStringTag,USP_tS:URLSearchParams.prototype.toString,D_pFS:DOMParser.prototype.parseFromString,U_cOU:URL.createObjectURL,U_rOU:URL.revokeObjectURL,X_o:XMLHttpRequest.prototype.open,X_pSD:XMLHttpRequest.prototype.DONE,X_pSH:XMLHttpRequest.prototype.HEADERS_RECEIVED,X_pSL:XMLHttpRequest.prototype.LOADING,X_pSO:XMLHttpRequest.prototype.OPENED,X_pSU:XMLHttpRequest.prototype.UNSENT,X_s:XMLHttpRequest.prototype.send,D_n:Date.now,I_tS:e=>""+e,
E_r:Element.prototype.remove,E_s:Element.prototype.setAttribute,E_rA:Element.prototype.removeAttribute,D_cS:r(Document.prototype,"currentScript").get,D_gRS:r(Document.prototype,"readyState").get,D_cE:Document.prototype.createElementNS,D_gEBT:Document.prototype.getElementsByTagName,M_aN:r(MutationEvent.prototype,"attrName").get,M_rN:r(MutationEvent.prototype,"relatedNode").get,C_d:r(CustomEvent.prototype,"detail").get,W_aEL:addEventListener,W_rEL:removeEventListener,parseInt,parseFloat,
CustomEvent,CompositionEvent,KeyboardEvent,MouseEvent,MutationEvent,MutationObserver,console:Object.assign({},console),Error,Uint8Array,Blob,ReadableStream,Number,String,Proxy,Window,FileReader,DOMParser,XMLHttpRequest,Function,RegExp,Promise,encodeURIComponent,decodeURIComponent,encodeURI,decodeURI,escape,unescape,atob,btoa,setTimeout,clearTimeout,setInterval,clearInterval,postMessage,dispatchEvent,alert,prompt,confirm,close,getElementById:e.Document.prototype.getElementById,
createEvent:e.Document.prototype.createEvent,createElement:e.Document.prototype.createElement})
})(e.unsafeWindow),{cSO:o,F_c:r,F_a:s,F_b:a,F_tS:i,A_fE:c,A_so:l,A_sh:d,A_j:u,A_iO:g,A_iA:p,O_a:m,O_k:f,O_v:v,O_dP:_,O_dPy:M,O_hOP:b,O_gOPN:h,O_gOPD:y,O_gOPDs:w,O_gPO:E,O_tS:S,J_p:R,J_s:G,M_f:L,M_r:I,M_m:O,M_mi:C,M_i:P,M_pA:x,M_pAT:k,N_tS:D,N_MSI:T,P_t:A,P_c:U,R_rABS:$,R_rAT:j,R_r:F,R_enq:N,R_cl:V,S_fCC:q,S_sl:X,S_su:B,S_iO:H,S_sp_nr:W,S_tr:K,S_rA_nr:J,S_cCA:z,S_tLC:Y,S_tUC:Q,Y_tST:Z,D_pFS:ee,D_cS:te,D_gRS:ne,D_cE:oe,D_gEBT:re,E_r:se,E_s:ae,E_rA:ie,M_aN:ce,M_rN:le,C_d:de,U_cOU:ue,U_rOU:ge,USP_tS:pe,X_o:me,X_s:fe,X_pSD:ve,X_pSH:_e,X_pSL:Me,X_pSO:be,X_pSU:he,D_n:ye,I_tS:we,W_aEL:Ee,W_rEL:Se,parseInt:Re,parseFloat:Ge,console:Le,encodeURIComponent:Ie,decodeURIComponent:Oe,encodeURI:Ce,decodeURI:Pe,escape:xe,unescape:ke,atob:De,btoa:Te,postMessage:Ae,dispatchEvent:Ue,alert:$e,prompt:je,confirm:Fe,close:Ne,getElementById:Ve,createEvent:qe,createElement:Xe,CustomEvent:Be,CompositionEvent:He,KeyboardEvent:We,MouseEvent:Ke,MutationEvent:Je,MutationObserver:ze,Uint8Array:Ye,FileReader:Qe,DOMParser:Ze,XMLHttpRequest:et,Function:tt,RegExp:nt,Promise:ot,Blob:rt,ReadableStream:st,Number:at,String:it,Proxy:ct,Window:lt}=n,dt=r,ut=s,gt=f,pt=v,mt=m,ft=_,vt=M,_t=h,Mt=y,bt=E,ht=w||(e=>{
const t=Gt({});for(const n in e)t[n]=Mt(e,n);return t}),yt=p,wt=L,Et=I,St=O,Rt=(e,t,n)=>dt(ut,e,t,n),Gt=o,Lt=(e,t,n)=>(vt(e,t,Gt({value:n,configurable:!0,enumerable:!0,writable:!0})),e),It=(e,t)=>Wt(e,t)?e[t]:void 0,Ot=(e,t)=>{const n=Mt(e,t);return n?Gt(n).value:void 0},Ct=(e,t)=>{const n=(e,t,o)=>{const r=Mt(e,t),s=r?Gt(r):void 0;let a;return s?s.enumerable?s.value:void 0:--o>=0&&(a=bt(e))?n(a,t,o):void 0};return n(e,t,5)},Pt=e=>{const t=(t,...n)=>Rt(e,t,n);return Lt(t,"wrappedJSObject",e),t
},xt=()=>e=>Pt(e),kt=Pt(a),Dt=R,Tt=e=>{const t=(e,n)=>{let o;if(null===e)o="null";else{const r=typeof e;if("object"===r){if(n){if(-1!=Bt(n,e))throw"Converting circular structure to JSON";Lt(n,n.length,e)}else n=[e];if(yt(e)){let r="";for(let o=0;o<e.length;o++){let s;s=Wt(e,o)?It(e,o):Ct(e,o);const a=t(s,n);r+=`${o?",":""}${void 0===a?"null":a}`}o=`[${r}]`}else{let r="";Ht(gt(e),(o=>{const s=t(e[o],n);void 0!==s&&(r+=`${r?",":""}${G(o)}: ${s}`)})),o=`{${r}}`}n.length-=1}else{
if("bigint"===r)throw"Do not know how to serialize a BigInt";o=G(e)}}return o};return t(e)},At=e=>{const t=R(e),n=e=>{const t=[];for(let n=0;n<e.length;n++)Lt(t,n,o(e[n]));return t},o=e=>{if(null===e);else if("object"==typeof e){if(yt(e))return n(e);{const t={};return Ht(gt(e),(r=>{const s=e[r];let a;a="object"==typeof s?yt(s)?n(s):o(s):s,Lt(t,r,a)})),t}}return e};return o(t)},Ut=xt()(l),$t=(e,t,n,...o)=>{const r=o||[],s=Nt(e,0,t),a=Nt(e,t,n),i=Nt(e,t+n);let c=qt([],s);return c=qt(c,r),
c=qt(c,i),Gt({result:c,removed:a})},jt=xt()(d),Ft=(e,t)=>{const n=[];return Ht(e,(e=>{t(e)&&Xt(n,e)})),n},Nt=(e,t,n)=>{const o=e.length;let r=t||0;if(r>=o)return[];r<0&&(r=St(0,o+r));let s=void 0===n?o:n;s<0&&(s=St(0,o+s)),s>o&&(s=o);const a=Gt({});for(let t=r;t<s;t++)a[t]=Ot(e,t);return pt(a)},Vt=xt()(u),qt=(e,...t)=>{let n=e.length;const o=Gt(e);for(let e=0;e<t.length;e++){const r=t[e],s=yt(r)?r:[r];for(let e=0;e<s.length;e++)o[n+e]=Ot(s,e);n+=s.length}return pt(o)},Xt=(e,t)=>{
let n=e.length||0;return Lt(e,n,t),n++,e.length=n},Bt=xt()(g),Ht=xt()(c),Wt=xt()(b),Kt=xt()(W),Jt=xt()(X),zt=Pt(S),Yt=bt({}),Qt=e=>{const t=Gt(e),n=_t(t);for(let e=0;e<n.length;e++){const o=n[e],r=t[o];null!==r&&"object"==typeof r&&bt(r)===Yt&&(t[o]=Qt(r))}return t},Zt=e=>{const t=Kt(zt(e)," ");return Jt(Vt(Nt(t,1)," "),0,-1)},en=(xt()(i),
xt()(P)),tn=x,nn=k,on=xt()(D),rn=T,sn=xt()(A),an=xt()(U),cn=xt()($),ln=xt()(j),dn=xt()(F),un=N?xt()(N):N,gn=V?xt()(V):V,pn=q,mn=xt()(B),fn=xt()(H),vn=xt()(K),_n=(xt()(J||function(e,t){return Vt(Kt(this,e),t)}),xt()(z)),Mn=xt()(Y),bn=xt()(Q),hn=Z,yn=Pt(ee),wn=Pt(te),En=Pt(ne),Sn=(Pt(oe),Pt(re),Pt(se)),Rn=Pt(ae),Gn=Pt(ie),Ln=Pt(ce),In=Pt(le),On=Pt(de),Cn=Pt(pe),Pn=(xt()(me),ve),xn=_e,kn=Me,Dn=be,Tn=he,An=(xt()(fe),ye),Un=ct,$n=at,jn=Be,Fn=We,Nn=Ke,Vn=Ye,qn=ze,Xn=rt,Bn=function(e,t){return Ot(e,t)
},Hn=Gt({addEventListener:!1,Array:!0,Blob:!0,close:!1,CustomEvent:!0,Date:!0,DOMParser:!0,Error:!0,Event:!0,FileReader:!0,KeyboardEvent:!0,location:!0,Math:!0,MouseEvent:!0,MutationEvent:!0,Number:!0,Object:!0,Promise:!0,ReadableStream:!0,removeEventListener:!1,Uint8Array:!0,XMLHttpRequest:!0}),Wn=(()=>{const e=Gt({getElementById:Ve,createEvent:qe,createElement:Xe,dispatchEvent:Ue,addEventListener,removeEventListener}),t=Gt({});return Ht(gt(e),(n=>{try{const o=e[n];t[n]=function(...e){
return Rt(o,zn.document,e)}}catch(e){t[n]=((e,t)=>{if(Qn.error(`Tampermonkey sandbox preparation ${t?"("+t+") ":""}failed. This usually is caused by a third-party extension.`,e),t)return()=>{}})(e,`document.${n}`)}})),t})(),Kn=Gt({top:!0,location:!0}),Jn=e,{unsafeWindow:zn,unsafeThis:Yn}=Jn;e.bridges=e.bridges||Gt({});const Qn=e.console=e.console||Gt({}),Zn=Gt({addEventListener:kt(Ee,zn),removeEventListener:kt(Se,zn)});Ht(gt(Kn),(async e=>{if(!Zn[e])try{const t=zn[e];if(null==t)return;Zn[e]=t
}catch(e){}})),Ht(gt(Hn),(async e=>{if(!Zn[e])try{let t=Ot(zn,e);if(void 0===t&&(Yn===zn||void 0===(t=Ot(Yn,e))))return;const n=Hn[e];Zn[e]=!1===n&&"function"==typeof t?kt(t,Yn):t}catch(e){}}));const eo=e=>{let t,n=[],o=!1;e((e=>{if(!o){if(n.length){const t=n;n=[],Ht(t,(t=>t(e)))}else t=e;o=!0}}));const r=Gt({then:e=>(o?e(t):Xt(n,e),r)});return r},{createEvent:to}=Wn,no=()=>on(An()+19831206*Et()+1,36),oo=async e=>{await null,e()},ro=()=>{const e=wn(zn.document);e&&(Gn(e,"nonce"),Sn(e))
},so=(()=>{const{console:t,bridges:n}=e,o=Gt({});let r;const s=(e,n,r,s)=>{let i,c=[],l=[],d=[],u=[];const g=()=>{l=[],d=[],u=[],v(),y=null,delete o[n]},p=t=>{e.send("port.message",Gt({response_id:n,value:t}))},m=e=>{s&&"messageId"in e&&Xt(c,e),p(e)},f=(e,t=!0)=>{i=e,t&&p(e)},v=()=>{i=void 0},_=Gt({addListener:e=>{Xt(l,e)}}),M=Gt({addListener:e=>{Xt(d,e)}}),b=Gt({addListener:e=>{Xt(u,e)}}),h=()=>{g(),e.send("port.message",Gt({response_id:n,disconnect:!0}))};let y=Gt(r?{postMessage:m,
connectMessage:f,stopReconnecting:v,onMessage:_,onDisconnect:M,onReconnect:b,disconnect:h}:{postMessage:m,onMessage:_,onDisconnect:M,disconnect:h});return o[n]=Gt({message:e=>{if(s&&(e=>"ack"in e)(e)){const{messageId:n}=e;(e=>{if(!e)return void t.warn("PortMessaging: no message id in ack message");if(i&&i.messageId===e)return;let n=-1;Ut(c,((t,o)=>t.messageId===e&&(n=o,!0))),-1!==n?(Ht(Nt(c,0,n),(e=>t.warn(`PortMessaging: message ${e.messageId} was not ack'ed!`,e))),
c=Nt(c,n+1)):t.warn(`PortMessaging: no one is waiting for ${e}`)})(n)}l&&Ht(l,(t=>t(e)))},disconnect:()=>{if(i&&r)return a(r,n),f(i),s&&Ht(c,(e=>p(e))),void(u&&Ht(u,(e=>e())));d&&Ht(d,(e=>e())),g()}}),y},a=(e,t)=>{n.first.send("port.message",Gt({response_id:t,connect:!0,destination:e}))};return Gt({message:(e,n)=>{let a;if(e.connect){if(!e.destination||!e.response_id)throw"invalid message";r&&r(e.destination,s(n,e.response_id))}else{if(!e.response_id)throw"invalid message"
;if(!(a=o[e.response_id]))return void t.warn("ports: unknown id",e.response_id,e);e.disconnect?a.disconnect():a.message(e.value)}},connect:function(e,t,o){const r=no();return a(e,r),s(n.first,r,t?e:void 0,o)},onConnect:Gt({addListener:e=>{r=e}})})})(),{bridges:ao}=e,io=Gt({}),co=Gt({});let lo=!0,uo=[];oo((()=>{lo=!1,Ht(uo,(({m:e,i:t})=>ao.first.send("console",[e,t]))),uo=[]})),Ht(["debug","log","info","warn","error"],(e=>{Lt(io,e,((...t)=>{const n=(e=>{const t=[];return Ht(e,(e=>{
Xt(t,(e=>Tt(e))(e))})),t})(t);if(lo)return Xt(uo,Gt({m:e,i:n}));ao.first.send("console",[e,n])}))}));const go=Gt(ht(zn.console)),po=Gt({});Ht(_t(Le),(e=>{const t=Gt(go[e]);po[e]=Gt({get:"value"in t?()=>t.value:t.get,enumerable:!0,configurable:!1})})),ft(co,po)
;const mo=["chrome"],fo=["GM.backgroundControl"],vo=["GM_addElement","GM.addElement","GM_addStyle","GM.addStyle"],_o=["GM_cookie","GM.cookie"],Mo=["GM_listValues","GM.listValues","GM_getValue","GM.getValue","GM_addValueChangeListener","GM.addValueChangeListener","GM_removeValueChangeListener","GM.removeValueChangeListener","GM_setValue","GM.setValue","GM_deleteValue","GM.deleteValue"],bo=["GM_download","GM.download"],ho=["GM_getResourceText","GM.getResourceText","GM_getResourceURL","GM.getResourceUrl"],yo=["GM_getTab","GM.getTab","GM_getTabs","GM.getTabs","GM_saveTab","GM.saveTab"],wo=["GM_log","GM.log"],Eo=["GM_notification","GM.notification"],So=["GM_openInTab","GM.openInTab"],Ro=["GM_registerMenuCommand","GM.registerMenuCommand","GM_unregisterMenuCommand","GM.unregisterMenuCommand"],Go=["GM_setClipboard","GM.setClipboard"],Lo=["GM_xmlhttpRequest","GM.xmlHttpRequest"],Io=["window.close"],Oo=["window.focus"],Co=["window.onurlchange"],Po=["GM_webRequest","GM.webRequest"],xo=Gt({
encode:e=>ke(Ie(e)),decode:e=>Oe(xe(e))}),ko=Gt({encode:e=>{let t="";for(let n=0;n<e.length;n++)t+=pn(255&_n(e,n));return Te(t)},decode:e=>De(e)}),Do=e=>{const t=new Vn(e.length);for(let n=0;n<e.length;n++)t[n]=_n(e,n);return t.buffer},To=(e,t)=>eo((n=>{const o=new Zn.FileReader;o.onload=()=>{n(dn(o))},o.onerror=e=>{Qn.warn(`unable to decode data ${e}`),n("")},t?ln(o,e,t):cn(o,e)})),{bridges:Ao}=e;let Uo=0,$o=0;const jo=Gt({}),Fo=Gt({}),No=function(e,t,n,o){const r=()=>{jo[n]&&(Rt(e,this,o),
delete jo[n])};"function"==typeof e&&(jo[n]=e,0===t?oo((()=>r())):Ao.first.send("setTimeout",Gt({t:t||1}),(()=>r())))},Vo=e=>{const t=Fo[e];t&&(t.disconnect(),delete Fo[e])},qo=(e,t,...n)=>{const o=no();return No(e,t,o,n),o},Xo=e=>{(e=>{delete jo[e]})(e)},Bo=e=>Vo(e),Ho=(e,t,...n)=>{const o=++$o;return t=St(t,1),No(e,t,o,n),o},Wo=(e,t,...n)=>{const o=++Uo;return function(e,t,n,o){if("function"==typeof e){const r=Fo[n]=so.connect("setInterval");r.onMessage.addListener((()=>{Fo[n]&&Rt(e,this,o)
})),r.onDisconnect.addListener((()=>Vo(n))),r.postMessage(Gt({method:"setInterval",t:t||1}))}}(e,t=St(t,1),o,n),o};let Ko;const Jo=t=>{const{contextId:n,bridges:o}=e,r=Gt({}),s=(e,t)=>Ut(t,(t=>-1!=Bt(e,t))),a=e=>function(){const t=(async e=>e)(Rt(e,this,arguments));return Lt(t,"then",(e=>sn(t,e))),Lt(t,"catch",(e=>an(t,e))),t},i=(e,t)=>function(...n){const o=[];if(void 0!==t)for(let e=0;e<t;e++)Xt(o,Bn(n,e)||void 0);return new Zn.Promise((t=>{Rt(e,this,qt(o,[t]))}))},c=(e,t)=>{let n
;const o=new Zn.Promise(((o,r)=>{const s=Gt({}),a=t.onload,i=t.ontimeout,c=t.onerror;Ht(gt(t),(e=>{s[e]=t[e]})),s.onerror=function(e){c?(o(e),Rt(c,this,arguments)):r(e)},s.ontimeout=function(e){i?(o(e),Rt(i,this,arguments)):r(e)},s.onload=function(e){o(e),a&&Rt(a,this,arguments)};const l=e(s).abort;!0===n?l():n=l}));return Lt(o,"abort",(()=>{"function"==typeof n?n():n=!0})),o};return Gt({of:e=>{const l=e.script,d=(()=>{const e=s(l.grant,Go),t=(e,t,r)=>{o.first.send("setClipboard",Gt({content:e,
info:t,id:n,uuid:l.uuid}),r?()=>r():null)};return Gt({GM_setClipboard:e?Gt({value:t}):void 0,"GM.setClipboard":e?Gt({get:()=>i(t,2)}):void 0})})(),u=(()=>{let t=[];const o=e.storage;let r=0,i=null;const c=s(l.grant,Mo),d=(e,t)=>{if("string"!=typeof e)return t;{const n=mn(e,0,1);switch(e=mn(e,1),n){case"b":return"true"===e;case"n":return $n(e);case"x":try{return xo.decode(ko.decode(e))}catch(t){return e}case"o":try{return At(e)}catch(e){Qn.log(`values: parseValueFromStorage: ${e}`)}return t
;case"u":return;default:return e}}},u=(e,n,o,r)=>{n!=o&&Ht(t,(t=>{if(t&&t.key==e&&t.cb)try{t.cb(e,d(n),d(o),r)}catch(t){Qn.warn(`values: change listener of "${e}" failed with: ${t.message}`)}}))},g=(e,t)=>{i&&i.postMessage(Gt({messageId:no(),method:"saveStorageKey",uuid:l.uuid,key:e,value:o.data[e],removed:t,id:n,ts:o.ts}))};c&&(i=so.connect("values",!0,!0),i.onDisconnect.addListener((()=>{Qn.warn("values: port disconnected"),i=null})),i.onMessage.addListener((e=>{if("ack"in e)return
;const{storage:t,removed:n}=e;if(!t)return;const r=t,s=gt(r);n&&Xt(s,n),Ht(s,(e=>{const t=o.data[e],n=r[e];void 0===n?delete o.data[e]:o.data[e]=n,u(e,t,n,!0)}))})),i.connectMessage(Gt({messageId:no(),method:"addStorageListener",uuid:l.uuid,id:n})));const p=(e,t)=>d(o.data[e],t),m=()=>gt(o.data),f=(e,n)=>{const o=++r,s=Gt({id:o,key:e,cb:n});return Xt(t,s),o},v=e=>{t=Ft(t,(t=>t.id!==e))},_=(e,t)=>{const n=o.data[e];o.ts=An(),o.data[e]=(e=>{const t=typeof e;let n,o=mn(t,0,1);switch(t){
case"object":try{n=o+Tt(e)}catch(e){return void Qn.log(e)}break;case"function":case"symbol":case"bigint":o="u",n=o+void 0;break;case"string":case"number":case"undefined":case"boolean":n=o+e;break;default:n=t}return n})(t),g(e),u(e,n,o.data[e],!1)},M=e=>{const t=o.data[e];o.ts=An(),delete o.data[e],g(e,!0),u(e,t,o.data[e],!1)};return Gt({GM_getValue:c?Gt({value:p}):void 0,"GM.getValue":c?Gt({get:()=>a(p)}):void 0,GM_listValues:c?Gt({value:m}):void 0,"GM.listValues":c?Gt({get:()=>a(m)}):void 0,
GM_addValueChangeListener:c?Gt({value:f}):void 0,"GM.addValueChangeListener":c?Gt({get:()=>a(f)}):void 0,GM_removeValueChangeListener:c?Gt({value:v}):void 0,"GM.removeValueChangeListener":c?Gt({get:()=>a(v)}):void 0,GM_setValue:c?Gt({value:_}):void 0,"GM.setValue":c?Gt({get:()=>a(_)}):void 0,GM_deleteValue:c?Gt({value:M}):void 0,"GM.deleteValue":c?Gt({get:()=>a(M)}):void 0})})(),g=(()=>{const e=s(l.grant,Co),t=(()=>{let e=[],t=null;return Gt({register:(o,r)=>{Xt(e,o),
t||(t=so.connect("onurlchange",!0),t.onMessage.addListener((t=>{if("ack"in t)return;const{url:n}=t;if(!n)return;const o=Gt({url:n});Ht(e,(e=>{Rt(e,r,[o])}))})),t.connectMessage(Gt({messageId:no(),method:"observeUrlChanges",uuid:l.uuid,id:n})))},unregister:n=>{let o;n&&(o=Bt(e,n))>-1&&(e=$t(e,o,1).result),t&&0===e.length&&(t.disconnect(),t=null)}})})();return Gt({"window.onurlchange":e?Gt({value:t}):void 0})})(),p=(()=>{const e=s(l.grant,ho),t=e=>{for(let t=0;t<l.resources.length;t++){
const n=l.resources[t];if(n.name==e){if(n.error)Qn.warn("@resource: "+n.error);else try{if("string"==typeof n.content)return xo.decode(n.content)}catch(e){}return""}}return null},n=e=>{for(let t=0;t<l.resources.length;t++){const n=l.resources[t];if(n.name==e){if(n.error)Qn.warn("@resource: "+n.error);else if("string"==typeof n.content){try{return`data:${n.meta||"application/octet-stream"};base64,${ko.encode(n.content)}`}catch(e){}return n.url}return""}}return null};return Gt({
GM_getResourceText:e?Gt({value:t}):void 0,"GM.getResourceText":e?Gt({get:()=>a(t)}):void 0,GM_getResourceURL:e?Gt({value:n}):void 0,"GM.getResourceUrl":e?Gt({get:()=>a(n)}):void 0})})(),m=(()=>{const e=s(l.grant,yo),t=(e,t)=>{o.first.send("tabs",Gt({action:"set",uuid:l.uuid,tab:e}),t?()=>t():null)},n=e=>{o.first.send("tabs",Gt({action:"get",uuid:l.uuid}),e?t=>{e(t||Gt({}))}:null)},r=e=>{o.first.send("tabs",Gt({action:"list",uuid:l.uuid}),e?t=>{e(t||Gt({}))}:null)};return Gt({GM_saveTab:e?Gt({
value:t}):void 0,"GM.saveTab":e?Gt({get:()=>i(t,1)}):void 0,GM_getTab:e?Gt({value:n}):void 0,"GM.getTab":e?Gt({get:()=>i(n)}):void 0,GM_getTabs:e?Gt({value:r}):void 0,"GM.getTabs":e?Gt({get:()=>i(r)}):void 0})})(),f=(()=>{const e=s(l.grant,Lo),o=e=>{const o=Qt(e);let s=!1,a=()=>{s=!0};const i=(e,t)=>{t=t||Gt({}),e&&qo((()=>{mt(t,r),Rt(e,t,[t])}),1)},c=o.url;"object"==typeof c&&c.href&&(o.url=c.href);const d=(e,t)=>{const n=Zt(e);if("Blob"===n||"File"===n){const o=e;To(o).then((e=>{t(Gt({type:n,
value:e,meta:o.type,name:o.name,lastModified:o.lastModified}))}))}else if("FormData"===n){const n=e,o=n.keys();let r;const s=Gt({}),a=[];for(;!(r=o.next()).done;)Xt(a,r.value);const i=()=>{if(a.length){const e=jt(a);let t=n.getAll(e);"[]"!==mn(e,-2)&&(t=Bn(t,0)),d(t,(t=>{s[e]=t,i()}))}else t(Gt({type:"FormData",value:s}))};i()}else if("URLSearchParams"===n)t(Gt({type:"URLSearchParams",value:Cn(e)}));else if("Array"===n||"Object"===n){const o=e;let r,s,a=0,i=0;if("Object"===n){const e=gt(o)
;s=t=>t<e.length?e[t]:null,r=Gt({})}else s=e=>e<o.length?e:null,r=[];const c=()=>{const e=s(a);null===e?t(Gt({type:n,value:r})):d(o[e],(t=>{r[e]=t,a++,i++<1024?c():(i=0,qo(c,1))}))};c()}else t(Gt({value:e}))},u=(e,t,n,o,r)=>{let s;if(n)"stream"==o&&(s=n);else if("arraybuffer"==o)s=t||Do(e||"");else if("blob"==o)s=new Zn.Blob([t||Do(e||"")],Gt({type:r}));else if("json"==o)s=At(e||"");else if("document"==o){const t=new Zn.DOMParser,n=Bn(Kt(r||"text/xml",";"),0);try{s=yn(t,e||"",n)}catch(e){s=null}
}else s=e||(t?(e=>{let t="";const n=new Vn(e);for(let e=0;e<n.length;e+=32687)t+=Rt(pn,null,n.subarray(e,e+32687));return t})(t):"");return s};return(e=>{if(o.url){const t=mn(o.url,0,5);if(-1!=Bt(["data:","blob:"],t))return e()}if(!o.data)return e();d(o.data,(t=>{o.binary&&(t.type="Blob"),o.data=t,o.data_type="typified",e()}))})((()=>{if(s)return s=!1,void i(o.onabort);let e,r,c,d=so.connect("xhr"),g=[],p=!1
;const{method:m,url:f,redirect:v,headers:_,cookie:M,binary:b,nocache:h,revalidate:y,timeout:w,context:E,responseType:S,overrideMimeType:R,anonymous:G,fetch:L,user:I,password:O,data:C,data_type:P}=o,x=Gt({method:m,url:f,redirect:v,headers:_,cookie:M,binary:b,nocache:h,revalidate:y,timeout:w,responseType:S,overrideMimeType:R,anonymous:G,fetch:L,user:I,password:O,data:C,data_type:P});if(x.headers){const e=x.headers;Ht(gt(e),(t=>{"cookie"===Mn(t)&&(x.cookie=`${e[t]}`,delete e[t])}))}let k,D,T,A
;d.postMessage(Gt({messageId:no(),method:"xhr",details:x,callbacks:Gt({onloadstart:!!o.onloadstart,onload:!!o.onload,ondone:!!o.onloadend,onreadystatechange:!!o.onreadystatechange,onerror:!0,onabort:!!o.onabort,ontimeout:!!o.ontimeout,onprogress:!!o.onprogress,onuploadprogress:!(!o.upload||!o.upload.onprogress),onpartial:!0}),id:n,location:Zn.location.href,uuid:l.uuid,no_blob:"js"==t.sandboxMode}));const U=S?Mn(S):"";let $,j=0,F=0;const N=async t=>{if(t&&(c||void 0!==e||void 0!==r)){
if(R?A=R:t&&(A=(e=>{const t=Gt({});return e&&Ht(Kt(e,"\n"),(e=>{const n=Kt(e,":");if(n.length<2)return;const o=Bn(n,0);if(!o)return;const r=Vt(Nt(n,1),":");t[Mn(vn(o))]=vn(r||"")})),t})(t.responseHeaders)["content-type"]),k=e,c)T=c.stream;else if(r){const e=r;if(D=e.buffer,-1==Bt(["blob","arraybuffer"],U)&&!k){let t;Ut([A,e.type],(e=>t=((e,t,n,o)=>{const r=fn(e,"charset=");if(-1==r)return;const s=mn(e,r+8),a=fn(s,";");return-1==a?o&&o.optionalEnd?s:void 0:mn(e,r+8,a)})(Mn(e||""),0,0,Gt({
optionalEnd:!0}))));const n=new Xn([D]);$=To(n,t),k=await $}$=void 0}else $&&await $;e=r=void 0}if(k||T||D){t.responseType=S,Ht(["response_data"],(e=>delete t[e]));const e=Gt({response:()=>u(k,D,T,U,A||"binary/octet-stream"),responseText:()=>u(k,D,T,"text",A),responseXML:()=>u(k,D,T,"document","text/xml")});Ht(gt(e),(n=>{vt(t,n,Gt({get(){try{return e[n]()}catch(e){Qn.warn(`${m}:`,e)}}}))}))}},V=[],q=async e=>{e&&Xt(V,e);{const e=jt(V);e&&e()}};"stream"===U&&q((async()=>{c=await eo((e=>{
const t=new Zn.ReadableStream(Gt({start:n=>{qo((()=>e(Gt({stream:t,ctrl:n}))),0)},cancel:()=>{c&&(c.canceled||a(),c.canceled=!0)}}))}))})),d.onMessage.addListener((t=>q((()=>(async t=>{if(!("ack"in t))if(t.onpartial){const n=t.data,o=n,s=o.partial,a=n.nada;if(c){if(c.canceled)return;const e=un||((e,t)=>e.enqueue(t));if(void 0!==s)e(c.ctrl,s);else if(void 0!==a){const t=new Vn(a.buffer);e(c.ctrl,t)}else Qn.error(`${m}:`,"data message without data?!")}else{let t;s&&Xt(g,s),a&&(t=a),
void 0!==o.index&&o.index!==o.length-1||(g.length&&(e=Vt(g,""),g=[]),r=t)}}else{const e=t.data;if(j=e.readyState||j,F=e.status||F,E&&(e.context=E),t.onload)await N(e),i(o.onreadystatechange,e),i(o.onload,e);else if(t.onreadystatechange)await N(e),4!=e.readyState&&i(o.onreadystatechange,e);else if(t.onerror)t.exception&&Qn.error(t.exception),i(o.onerror,e);else if(t.onabort)i(o.onabort,e);else if(t.ondone)p=!0,c&&!c.canceled&&(gn||(e=>e.close()))(c.ctrl),await N(e),
i(o.onloadend,e);else if(t.onloadstart)c&&await N(e),i(o.onloadstart,e);else if(t.onuploadprogress)o.upload&&i(o.upload.onprogress,e);else{const n=Bn(Ft(["onprogress","ontimeout"],(e=>!!t[e])),0)||"onerror";i(o[n],e)}}})(t))))),d.onDisconnect.addListener((()=>{p||i(o.onerror,Gt({readyState:j,status:F,error:"background shutdown"})),d=null})),a=()=>{d&&d.postMessage(Gt({messageId:no(),cancel:!0}))}})),Gt({abort:()=>{a()}})},r=(()=>{const e=Gt({DONE:Pn,HEADERS_RECEIVED:xn,LOADING:kn,OPENED:Dn,
UNSENT:Tn});return Ht(["text","arraybuffer","blob","document","json","stream"],(t=>{e[`RESPONSE_TYPE_${bn(t)}`]=t})),e})();return Ht(gt(r),(e=>Lt(o,e,r[e]))),Gt({GM_xmlhttpRequest:e?Gt({value:o}):void 0,"GM.xmlHttpRequest":e?Gt({get:()=>{const e=e=>c(o,e);return Ht(gt(r),(t=>Lt(e,t,r[t]))),e}}):void 0})})(),v=(()=>{let n;const o=()=>{if(!n){
const{script:o}=e,{antifeatures:r,author:s,blockers:a,copyright:i,deleted:c,description_i18n:l,description:d,downloadURL:u,fileURL:g,grant:p,header:m,homepage:f,icon:v,icon64:_,lastModified:M,name_i18n:b,name:h,namespace:y,position:w,resources:E,supportURL:S,system:R,updateURL:G,version:L,webRequest:I,options:{override:{orig_connects:O,orig_excludes:C,orig_includes:P,orig_matches:x},run_at:k,unwrap:D}}=o,{downloadMode:T,inIncognitoContext:A,relaxedCsp:U,isFirstPartyIsolation:$,sandboxMode:j,userAgent:F,version:N}=t,V=G||g,q=Gt({
antifeatures:r,author:s,blockers:a,connects:O,copyright:i,deleted:c,description_i18n:l,description:d,downloadURL:u,excludes:C,fileURL:g,grant:p,header:m,homepage:f,icon:v,icon64:_,includes:P,lastModified:M,matches:x,name_i18n:b,name:h,namespace:y,options:o.options,position:w,resources:E,"run-at":k,supportURL:S,system:R,unwrap:D,updateURL:G,version:L,webRequest:I}),X=Gt({downloadMode:T,isFirstPartyIsolation:$,isIncognito:A,relaxedCsp:U,sandboxMode:j,script:q,scriptHandler:"Tampermonkey",
scriptMetaStr:o.header,scriptUpdateURL:V,scriptWillUpdate:!!V,userAgentData:F,version:N});n=X}return At(Tt(n))};return Gt({GM_info:Gt({get:o}),"GM.info":Gt({get:o})})})(),_=(()=>{const e=s(l.grant,Po);let t=null;const n=(e,n)=>{const o=()=>{t==r&&(t=null),r=null};t&&t.disconnect();let r=t=so.connect("webRequest",!0);return n&&r.onMessage.addListener((e=>{"ack"in e||n(e.type,e.message||"ok",e.details)})),r.onDisconnect.addListener(o),r.connectMessage(Gt({messageId:no(),rules:e,uuid:l.uuid})),Gt({
abort:()=>{r&&r.disconnect(),o()}})};return Gt({GM_webRequest:e?Gt({value:n}):void 0,"GM.webRequest":e?Gt({get:()=>a(n)}):void 0})})(),M=(()=>{const e=s(l.grant,Ro);let t=0;const n=Gt({}),o=(e,o,s)=>{if("string"!=typeof e)throw"invalid name";const a=so.connect("registerMenuCommand",!0),{accessKey:i,autoClose:c,title:d,id:u}="string"==typeof s?Gt({accessKey:s}):s||Gt({}),g=void 0!==u?u:++t;a.onMessage.addListener((e=>{if(!("ack"in e)&&"run"===e.method){
const t=e.event,n=t?t.keyCode?new Fn("keypress",t):new Nn("click",e.event):void 0;qo((()=>o(n)),1)}})),a.onDisconnect.addListener((()=>{r(g)})),a.connectMessage(Gt({messageId:no(),name:e,uuid:l.uuid,accessKey:i,autoClose:c,title:d,id:`${g}`}));const p=n[g];return p&&p(),n[g]=a.disconnect,g},r=e=>{let t;(t=n[e])&&(t(),delete n[e])};return Gt({GM_registerMenuCommand:e?Gt({value:o}):void 0,"GM.registerMenuCommand":e?Gt({get:()=>a(o)}):void 0,GM_unregisterMenuCommand:e?Gt({value:r}):void 0,
"GM.unregisterMenuCommand":e?Gt({get:()=>a(r)}):void 0})})(),b=(()=>{const e=s(l.grant,Eo),t=(e,t,n,o)=>{let r,s,a=null;const i=e=>Vt([e?`tag-${e}`:no(),l.uuid],"#");if("object"==typeof e){const n=e,{timeout:c,text:d,image:u,title:g,highlight:p,silent:m,url:f,tag:v}=n;s=i(v),r=Gt({id:s,timeout:c,text:d,image:u||l.icon64||l.icon||void 0,title:g||l.name,highlight:p,silent:m,url:f,tag:v}),a=n.ondone,o=n.onclick,"function"==typeof t&&(a=t)}else s=i(),r=Gt({id:s,text:e,
title:"string"==typeof t?t:l.name,image:n||l.icon64||l.icon||void 0});r.onclick=o,r.ondone=a||void 0,((e,t)=>{const{text:n,title:o,tag:r,url:s,image:a,highlight:i,silent:c,timeout:d,onclick:u,ondone:g}=Qt(t);if(n||i){const t="notification",p=so.connect(t,!0);p.onMessage.addListener((e=>{if("ack"in e)return;const{clicked:t}=e;let l=!1;const m=Gt({text:n,title:o,tag:r,url:s,image:a,highlight:i,silent:c,timeout:d,preventDefault:()=>{l=!0}});t&&(u&&u(m),p.postMessage(Gt({messageId:no(),canceled:l
}))),g&&g(!0===t,m),p.disconnect()})),p.connectMessage(Gt({messageId:no(),method:"notification",id:e,uuid:l.uuid,text:n,title:o,tag:r,url:s,image:a,highlight:i,silent:c,timeout:d}))}else Qn.warn("GM_notification: neither a message text nor highlight options were given!")})(s,r)};return Gt({GM_notification:e?Gt({value:t}):void 0,"GM.notification":e?Gt({get:()=>(e,n,o,r)=>{let s;return s="object"==typeof e?e:Gt({text:e,title:n,image:o,onclick:r}),new Zn.Promise((e=>{const n=Gt({});Ht(gt(s),(e=>{
n[e]=s[e]}));const o=n.ondone;n.ondone=function(t,n){o&&Rt(o,this,[t,n]),Rt(e,this,[t])},t(n)}))}}):void 0})})(),h=(()=>{const e=s(l.grant,_o),t=(e,t)=>Gt({action:e,uuid:l.uuid,location:Zn.location.href,details:t}),n=Gt({set:(e,n)=>{o.first.send("cookie",t("set",e),n?e=>{n(e.error)}:null)},delete:(e,n)=>{o.first.send("cookie",t("delete",e),n?e=>{n(e.error)}:null)},list:(e,n)=>{o.first.send("cookie",t("list",e),n?e=>{n(e.cookies,e.error)}:null)}});return Gt({GM_cookie:e?Gt({get:()=>{
const e=(e,t,o)=>(n[e]||(()=>{}))(t,o);return Ht(gt(n),(t=>{Lt(e,t,n[t])})),e}}):void 0,"GM.cookie":e?Gt({get:()=>{const e=Gt({});return Ht(gt(n),(t=>{e[t]=e=>((e,t)=>new Zn.Promise(((o,r)=>{if("list"==e){const s=t;n[e](s,((e,t)=>{t?r(t):o(e)}))}else if("set"==e){const s=t;n[e](s,(e=>{e?r(e):o(void 0)}))}else{const s=t;n[e](s,(e=>{e?r(e):o(void 0)}))}})))(t,e)})),e}}):void 0})})(),y=(()=>{const e=s(l.grant,bo),t=(e,t)=>"object"==typeof e?e:Gt({url:e,name:t,headers:void 0,saveAs:void 0,
conflictAction:void 0,onprogress:void 0,onload:void 0,ondone:void 0,ontimeout:void 0,onerror:void 0}),n=(e,n)=>{const o=t(e,n),r=(e,t)=>{t=t||Gt({}),e&&qo((()=>{Rt(e,t,[t])}),1)},{url:s,name:a,headers:i,saveAs:c,conflictAction:d}=o;let u,g=so.connect("download",!0);const p=()=>{g&&g.stopReconnecting()};g.onMessage.addListener((e=>{if(!("ack"in e)){g&&void 0===u&&(u=e.id,g.connectMessage(Gt({messageId:no(),method:"download",uuid:l.uuid,id:u}),!1));try{e.load?(o.onload&&r(o.onload,e.data),
p()):e.progress?o.onprogress&&r(o.onprogress,e.data):e.timeout?(o.ontimeout&&r(o.ontimeout,e.data),p()):(o.onerror&&r(o.onerror,e.data),p())}catch(e){Qn.log("env: Error: TM_download - ",e,o)}}})),g.onDisconnect.addListener((()=>g=null));const m=Gt({messageId:no(),details:Gt({url:s,name:a||"File.download",headers:i,conflictAction:d,saveAs:c}),uuid:l.uuid});return g.postMessage(m),Gt({abort:()=>{g&&g.postMessage(Gt({uuid:l.uuid,cancel:!0}))}})};return Gt({GM_download:e?Gt({value:n}):void 0,
"GM.download":e?Gt({get:()=>(e,o)=>c(n,t(e,o))}):void 0})})(),w=(()=>{const e=s(l.grant,So),t=(e,t)=>{const n="openInTab";let o,r,s=!1,a=null;const i=(()=>{const e=[];return Gt({run:t=>{if(t&&Xt(e,t),o)for(;e.length;)jt(e)()}})})();let c=so.connect(n,!0);const d=()=>{c&&c.postMessage(Gt({messageId:no(),close:!0}))};c.onMessage.addListener((e=>{"ack"in e||(e.tabId?s?d():(c&&void 0===o&&c.connectMessage(Gt({messageId:no(),method:n,uuid:l.uuid,tabId:e.tabId}),!1),o=e.tabId,
i.run()):e.name?r=e.name:e.closed&&(s=!0,a&&(a(),a=null),c&&c.stopReconnecting()))})),c.onDisconnect.addListener((()=>c=null)),c.postMessage(Gt({messageId:no(),method:n,url:e,location:Zn.location.href,options:t,uuid:l.uuid}));const u=Gt({});return ft(u,Gt({close:Gt({value:()=>{s?Qn.warn("env: attempt to close already closed tab!"):d()}}),focus:Gt({value:()=>{c&&c.postMessage(Gt({messageId:no(),focus:!0}))}}),closed:Gt({get:()=>s}),onclose:Gt({get:()=>a,set:e=>{a=e}}),name:Gt({get:()=>r,set:e=>{
i.run((()=>{c&&c.postMessage(Gt({messageId:no(),name:e}))}))}})})),u};return Gt({GM_openInTab:e?Gt({value:t}):void 0,"GM.openInTab":e?Gt({get:()=>a(t)}):void 0})})(),E=(()=>{const e=s(l.grant,Io);return Gt({"window.close":e?Gt({value:e=>{o.first.send("closeTab",Gt({uuid:l.uuid}),e?()=>e():null)}}):void 0})})(),S=(()=>{const e=s(l.grant,Oo);return Gt({"window.focus":e?Gt({value:e=>{o.first.send("focusTab",Gt({uuid:l.uuid}),e?()=>e():null)}}):void 0})})(),R=(()=>{
const e=s(l.grant,wo),t=function(...e){Rt(Qn.log,this,e)};return Gt({GM_log:e?Gt({value:t}):void 0,"GM.log":e?Gt({get:()=>a(t)}):void 0})})(),G=({root:e,tag:t,properties:n,cb:r})=>{const s=no(),a=Gt({tag:t,properties:n,id:s,uuid:l.uuid});o.first.send("addElement",a,e,r?()=>r():null);const i=Wn.getElementById(s),c=n?n.id:void 0;return void 0!==c&&Rn(i,"id",c),i},L=(()=>{const e=s(l.grant,vo),t=(e,t)=>G(Gt({root:void 0,tag:"style",properties:Gt({textContent:e}),cb:t}));return Gt({
GM_addStyle:e?Gt({value:t}):void 0,"GM.addStyle":e?Gt({get:()=>a(t)}):void 0})})(),I=(()=>{const e=s(l.grant,vo),t=(e,t,n,o)=>{let r,s,a,i;return"string"==typeof e?(s=e,a=t,i=n):(r=e,s=t,a=n,i=o),a&&(a=Gt(a)),G(Gt({root:r,tag:s,properties:a,cb:i}))};return Gt({GM_addElement:e?Gt({value:t}):void 0,"GM.addElement":e?Gt({get:()=>a(t)}):void 0})})(),O=(()=>{const e=s(l.grant,fo),t=(e,t)=>{const o="backgroundControl",r=so.connect(o);let s=!1;const a="restart"===e.action||void 0
;r.onMessage.addListener((e=>{if("ack"in e)return;s=!0;const n=e?e.error:void 0;n&&Qn.warn(n),t&&t(n),r.disconnect()})),r.postMessage(Gt({messageId:no(),method:o,id:n,uuid:l.uuid,restart:a})),a&&(Ko=!1),r.onDisconnect.addListener((()=>{!s&&t&&t(a?void 0:"port disconnected for unknown reason"),s=!0}))};return Gt({"GM.backgroundControl":e?Gt({get:()=>a(t)}):void 0})})(),C=Gt({...I,...L,...E,...h,...y,...S,...v,...R,...M,...b,...w,...p,...d,...m,...g,...u,..._,...f,...O})
;return r[e.script.uuid]=r[e.script.uuid]||C,r[e.script.uuid]}})},zo=(e,t,n,o,r,s)=>{const a=(e,t,n,o,r)=>{const a=t[n],i=typeof a;return o&&"string"===i?t[n]=()=>s(a,r):r&&"function"===i&&(t[n]=function(){return Rt(a,r,arguments)}),Rt(e,zn,t)};let i=!0;oo((()=>i=!1));const c=Gt({}),l=e=>!!("object"==typeof e&&null!==e?e.capture:e),d=(e,o,r)=>{let d,g;null===o||("object"==typeof o?(d=async e=>{const t=o.handleEvent;"function"==typeof t&&Rt(t,o,[e])},g=o):(d=o,g=void 0));const m=l(r);let f,v
;if(void 0!==d&&i&&((f="DOMContentLoaded"==e)||"load"==e)){const n=En(zn.document);if(f&&("complete"==n||"interactive"===n)&&"document-idle"!=t||!f&&"complete"==n)return void(async(e,t,n,o)=>{const r=Gt({attrName:"null",newValue:"null",prevValue:"null",eventPhase:nn,attrChange:tn,target:zn.document,relatedNode:zn.document,srcElement:zn.document});await null,n||await null,"load"===e&&await null,((e,t,n,o)=>{const r=Gt({attrChange:0,attrName:null,bubbles:!0,cancelBubble:!1,cancelable:!1,
clipboardData:void 0,currentTarget:null,defaultPrevented:!1,eventPhase:0,newValue:null,prevValue:null,relatedNode:null,returnValue:!0,srcElement:null,target:null,timeStamp:An()}),a="string"==typeof n?()=>s(n,o):n,i=new Event(e);Ht(gt(r),(e=>{Lt(i,e,r[e])})),Ht(gt(t),(e=>{Lt(i,e,t[e])})),Rt(a,o,[i])})(e,r,t,o)})(e,d,m,p)}const _="urlchange"==e?n["window.onurlchange"]:void 0;if(void 0===d);else if("string"!=typeof d){const t=`${e}-${m}`;c[t]=c[t]||[];const n=function(...t){
return"object"==typeof r&&r.once&&u(e,o,r),Rt(d,this===zn||this===Yn?p:this,t)},s=Gt({listener:d,filter:n,object:g});if(Xt(c[t],s),v=n,_)return void _.value.register(n)}else{if(_)return void Qn.warn("env: urlchange listener must be a function!");v=d}return a(Zn.addEventListener,[e,v,r],1,!0)},u=(e,t,o)=>{let r,s;null===t||("object"==typeof t?s=t:r=t);const i="urlchange"==e?n["window.onurlchange"]:void 0,d=l(o),u=`${e}-${d}`,g=c[u]&&Ft(c[u],(e=>e.object?e.object===s:e.listener===r))
;if(g&&g.length){let t;if(Ht(g,(n=>{if(i)i.value.unregister(n.filter);else try{a(Zn.removeEventListener,[e,n.filter,o],1,!0)}catch(n){t=n}const r=Bt(c[u],n);c[u]=$t(c[u],r,1).result})),c[u].length||delete c[u],t)throw t}else if(void 0!==r)return a(Zn.removeEventListener,[e,r,o],1,!0)},g=Gt({CDATA:Gt({value:function(e){this.src=e,this.toString=function(){return this.src},this.toXMLString=this.toString}}),uneval:Gt({value:e=>{try{return`\\$1 = ${Tt(e)};`}catch(e){Qn.log(e)}}}),define:Gt({
value:void 0}),module:Gt({value:void 0}),exports:Gt({value:void 0}),setTimeout:Gt({value:(...e)=>a(Ho,e,0,!0,p)}),setInterval:Gt({value:(...e)=>a(Wo,e,0,!0,p)}),close:(()=>{const e=n["window.close"];return e?Gt({get:()=>zn==zn.top?t=>e.value(t):Zn.close}):void 0})(),focus:(()=>{const e=n["window.focus"];return e?Gt({get:()=>t=>e.value(t)}):void 0})(),onurlchange:n["window.onurlchange"]?(()=>{let e=null;return Gt({get:()=>e,set:t=>{e&&u("urlchange",e),e=t,d("urlchange",e)}})})():void 0,
location:Gt({set:e=>{Zn.location.href=e}}),name:Gt({get:()=>zn.name,set:e=>{zn.name=e}}),clearInterval:Gt({get:()=>Bo}),clearTimeout:Gt({get:()=>Xo}),addEventListener:Gt({value:d}),removeEventListener:Gt({value:u}),console:Gt({get:()=>co})});if(!e){const e=Gt({window:Gt({get:()=>p}),globalThis:Gt({get:()=>p}),cloneInto:Gt({value:e=>e}),exportFunction:Gt({value:(e,t,n)=>{const o=n&&It(n,"defineAs");return o&&(t[o]=e),e}}),createObjectIn:Gt({value:(e,t)=>{const n=Gt({}),o=t&&It(t,"defineAs")
;return o&&(e[o]=n),n}}),undefined:Gt({get:()=>{}})});mt(g,e)}o&&mt(g,o);const p=r(g);return p};let Yo;(async()=>{const n=e.contextId;let o;const{fSend:r,fOnMessage:s,cloneInto:a,pageWindow:i}=e;o=r&&s?(({sendPrefix:e,listenPrefix:t,send:n,onMessage:o})=>{if(void 0===n||void 0===o)throw"invalid args";let r,s,a=1;const i=Gt({}),c=Gt({}),l=e=>{e&&(r=e)},d=e=>{const t=++a;return c[a]=e,t};o(((o,a)=>o==`${t}_${r}`?(t=>{const{m:o,r:a,a:l,n:d}=t;if(i[o]&&(Ht(i[o],(e=>e(l))),delete i[o]),
"message.response"==o){if(null==a)throw"Invalid Message";((e,t)=>{let n;e&&(n=c[e])&&(n(t),delete c[e])})(a,l)}else if(s){const t=a?t=>{n(`${e}_${r}`,Gt({m:"message.response",a:t,r:a}))}:()=>{};s(Gt({method:o,args:l,node:d}),t)}})(a):null));const u=Gt({init:async e=>{r?l():l(e)},refresh:()=>null,switchId:e=>{r&&u.cleanup(),l(e)},send:(t,o,s,a)=>eo((i=>{let c,l;"function"!=typeof s&&null!==s?(c=s,l=a):l=s,n(`${e}_${r}`,Gt({m:t,a:o,r:l?d(l):null,n:c})),i()})),sendToId:(t,o,r)=>{n(`${e}_${t}`,Gt({
m:o,a:r,r:null}))},once:(e,t)=>{i[e]||(i[e]=[]),Xt(i[e],t)},setMessageListener:e=>{s=e},cleanup:()=>null});return u})(Gt({sendPrefix:"2U",listenPrefix:"2S",send:r,onMessage:s})):(({sendPrefix:e,listenPrefix:n,cloneInto:o})=>{const r=Gt({});let s,a,i=1;const c=Gt({});let l=!1,d=[];const u=()=>{v=zn.document.documentElement,l=!1;const e=d;d=[],Ht(e,(e=>{l||M()?Xt(d,e):e()}))},g=e=>{const t=++i;return c[i]=e,t},p=(e,t)=>{const{m:n,a:r,r:s,n:a}=t,i=((e,t,n)=>{let r;var s
;return n?(r=to("MutationEvent"),en(r,e,!1,!1,n||null,void 0,void 0,Tt(t),tn)):r=new jn(e,Gt({detail:(s=t,o?o(s,zn.document):s)})),r})(e,Gt({m:n,a:r,r:s}),a);Rt(Ue,zn,[i])},m=t=>{const{m:n,r:o,a:i}=Qt("CustomEvent"==Zt(l=t)?On(l):Dt(Ln(l)));var l;if(r[n]&&(Ht(r[n],(e=>e(i))),delete r[n]),"unlock"==n)p(`${e}_${a}`,Gt({m:"unlocked",a:void 0,r:null})),u();else if("unlocked"==n)u();else if("message.response"==n){if(null==o)throw"Invalid Message";((e,t)=>{let n;e&&(n=c[e])&&(n(t),delete c[e])})(o,i)
}else if(s){const r=o?t=>{p(`${e}_${a}`,Gt({m:"message.response",a:t,r:o}))}:()=>{};s(Gt({method:n,args:i,node:"MutationEvent"===Zt(t)?In(t):void 0}),r)}},f=e=>{e&&(a=e),a&&Zn.addEventListener(`${n}_${a}`,m,!0)};let v,_;const M=()=>{if((()=>{const e=zn.document.documentElement;return v||(v=e),v!==e})()){if(_){const e=_;_=void 0,e(zn.document)}return!0}},b=Gt({init:async(n,o)=>{a?f():f(n),t&&!o&&await null,(v=zn.document.documentElement,eo((e=>{_=e;const t=new qn((()=>{M()&&t.disconnect()}))
;t.observe(zn.document,Gt({childList:!0}))}))).then((()=>{l=!0,b.refresh(),p(`${e}_${a}`,Gt({m:"unlock",a:void 0,r:null}))}))},refresh:()=>{const e=a;e&&(b.cleanup(),b.init(e,!0))},switchId:e=>{a&&b.cleanup(),f(e)},send:(t,n,o,r)=>eo((s=>{let i,c;"function"!=typeof o&&null!==o?(i=o,c=r):c=o,M();const u=()=>{p(`${e}_${a}`,Gt({m:t,a:n,r:c?g(c):null,n:i})),s()};l?Xt(d,u):u()})),sendToId:(t,n,o)=>{p(`${e}_${t}`,Gt({m:n,a:o,r:null}))},setMessageListener:e=>{s=e},once:(e,t)=>{r[e]||(r[e]=[]),
Xt(r[e],t)},cleanup:()=>{a&&(Zn.removeEventListener(`${n}_${a}`,m,!0),a=void 0)}});return b})(Gt({sendPrefix:"2C",listenPrefix:"2P"})),e.bridges.first=o;const c=mt(e.console,io);o.init(n);const l=Gt({});o.setMessageListener((({method:t,args:n})=>{if("commid"==t)o.switchId(n.id),o.send("ack",Gt({id:n.id}));else if("injectable"==t)g(n.id,(()=>{o.send("ack",Gt({id:n.id}))})),o.send("injectableack",Gt({id:n.id}));else if("setForeignAttr"==t)zn[n.attr]=n.value;else if("script"==t){
const{id:t,unwrap:r,bundle:s}=n,{script:a}=s,{name:i,uuid:c,options:{run_at:u}}=a;g(t,(t=>{const o=r?()=>t():()=>Rt(t,((t,n,o,r)=>{const{pageWindow:s,cloneInto:a,exportFunction:i}=e,c=s||zn,{script:l}=t,d=l.options.compat_powerful_this,u=-1!==Bt(l.grant,"none");Yo=Yo||Jo(n);const g=Yo.of(t),p=e=>Gt({p:v,r:Rt,s:e}),m=Gt({seed:Gt({get:()=>p(M),once:!0})}),f=Gt({}),v=Gt({GM:f}),_=c&&c;d&&(Lt(m,"GM",Gt({value:f})),Lt(m,"unsafeWindow",Gt({value:_}))),u||(v.unsafeWindow=_),Ht(gt(g),(e=>{
const t=mn(e,0,3),n=g[e];if(void 0!==n)if("GM_"===t)v[e]=void 0!==n.get?n.get():n.value,d&&Lt(m,e,n);else if("GM."===t){const t=Jt(e,3);vt(f,t,n)}}));const M=u?p(d?v:Gt({})):zo(u,l.options.run_at,g,m,o,r);return M})(s,n.flags,d,p),[]);"document-start"==u||"context-menu"==u?o():l[c]=o})),o.send(`scriptack-${t}`,Gt({id:t}))}else if("port.message"==t)so.message(n,o);else if("external.connect"==t)(t=>{const{bridges:n}=e,o=zn,r=It(o,"external");if(!r)return;const s=t?e=>t(e,o,Gt({cloneFunctions:!0
})):e=>e,a=(e,t)=>{n.first.send("external.message",e,t)};try{const e=()=>{const e=Gt({getVersion:e=>{a(Gt({method:"getVersion"}),(t=>e(s(t))))},openOptions:(e,t)=>{a(Gt({method:"openOptions",params:e}),t)},isInstalled:(e,t,n)=>{"function"==typeof t&&(n=t,t=null),a(Gt({method:"isInstalled",script:Gt({name:e,namespace:t})}),(e=>n(s(e))))}});return s(e)};ft(r,Gt({Tampermonkey:Gt({value:e(),configurable:!0})}))}catch(e){}})(a);else if("run"==t){const{uuid:e}=n,t=It(l,e);t?"function"==typeof t&&(t(),
delete l[e]):c.warn(`env: missing script "${e}"!`)}}));const{createProxy:d}=((e,t)=>{const n=(e=>{let t=Gt({});const n=(e,o,r)=>{const s=bt(e);s&&s===o||(null!=s&&--r>=0&&n(s,e,r),t=mt(t,ht(e)))};return n(e,null,5),t})(zn);Ht(mo,(e=>delete n[e]));const o=n;return Gt({createProxy:n=>{let r=o;const s=e=>{let t,n;const o=(t=Mt(p,e))||(n=r[e]);return Gt({d:o?Gt(o):o,l:!!t,w:!!n})},a=e=>{if(!c(e))return!1;if("length"===e)return!0;const t=wt($n(e));return t>=0&&t<=rn&&e===`${t}`
},i=e=>"on"===mn(e,0,2),c=e=>"string"==typeof e,l=(e,n)=>{const o=mn(e,2),r=g[o];if(r&&(t.removeEventListener(o,r),delete g[o]),n&&(e=>"function"==typeof e)(n)){const e=(...e)=>Rt(n,t,e);t.addEventListener(o,e),g[o]=e}},d=t=>void 0!==t&&(t===e||t===zn||t===Yn),u=Gt({addEventListener:!0,alert:!0,atob:!0,blur:!0,btoa:!0,cancelAnimationFrame:!0,cancelIdleCallback:!0,captureEvents:!0,clearInterval:!0,clearTimeout:!0,close:!0,confirm:!0,createImageBitmap:!0,dispatchEvent:!0,dump:!0,fetch:!0,find:!0,
focus:!0,getComputedStyle:!0,getDefaultComputedStyle:!0,getSelection:!0,matchMedia:!0,moveBy:!0,moveTo:!0,open:!0,openDatabase:!0,postMessage:!0,print:!0,prompt:!0,queueMicrotask:!0,releaseEvents:!0,removeEventListener:!0,reportError:!0,requestAnimationFrame:!0,requestIdleCallback:!0,resizeBy:!0,resizeTo:!0,scroll:!0,scrollBy:!0,scrollByLines:!0,scrollByPages:!0,scrollTo:!0,setInterval:!0,setResizable:!0,setTimeout:!0,showDirectoryPicker:!0,sizeToContent:!0,stop:!0,structuredClone:!0,
updateCommands:!0,webkitCancelAnimationFrame:!0,webkitRequestAnimationFrame:!0,webkitRequestFileSystem:!0,webkitResolveLocalFileSystemURL:!0});Ht(gt(u),(e=>{n[e]=n[e]||Gt({bind:!0})}));const g=Gt({}),p=Gt({});Lt(p,hn,"Window");const m=new Un(p,Gt({defineProperty:(e,t,o)=>{const{d:r,l:d}=s(t),u=Gt(o);return r&&!r.configurable&&(!!r.configurable!=!!u.configurable||!!r.enumerable!=!!r.enumerable)||a(t)?(vt(d?p:zn,t,u),!1):(vt(p,t,u),c(t)&&i(t)&&l(t),delete n[t],!0)},deleteProperty:(e,t)=>{
let{d:a,l:d,w:u}=s(t);return!(!a||!a.configurable)&&(d&&(d=delete p[t],c(t)&&i(t)&&l(t)),(u||(a=r[t])&&a.configurable)&&(o===r&&(r=mt(Gt({}),o)),u=delete r[t]),delete n[t],d||u)},get:(e,t)=>{const o=n[t];if(o){if(o.once&&delete n[t],"value"in o)return o.value;if(o.get)return o.get()}const{d:r,l:i}=a(t)?Gt({d:Mt(zn,t),l:!1}):s(t);if(r){let e;const n="value"in r?It(r,"value"):(e=It(r,"get"))&&"function"==typeof e?i?e():kt(e,zn)():void 0
;return n&&o&&o.bind?kt(n,zn):i||"event"==t?n:d(n)||"globalThis"===t?m:n}},getOwnPropertyDescriptor:(e,t)=>{let{d:o,l:r}=s(t);if(!o){const e=n[t];if(e)return Gt({enumerable:!0,configurable:!0,writable:!0,value:e.value,set:e.set,get:e.get});if(!a(t))return;o=Mt(zn,t),r=!1}const i=mt(Gt({}),o);if(d(i.value)&&(i.value=m),!r){const e=i.get;e&&(i.get=()=>{const t=kt(e,zn)();return d(t)?m:t}),i&&!i.configurable&&vt(p,t,i)}return i},has:(e,t)=>t in p||t in n||t in r,ownKeys:()=>{
const e=e=>!(e in r),t=gt(r),n=Ft(gt(ht(p)),e),o=Gt({});for(let e=0;"Window"===Zt(Ot(zn,e));e+=1)o[e]=!0;const s=Ft(gt(o),e);return qt(t,n,s)},preventExtensions:()=>!0,set:(e,t,o)=>{const r=n[t];if(r&&r.set)return r.set(o),!0;const{d}=s(t);return!(d&&!d.writable&&!It(d,"set")||a(t)||(delete n[t],Lt(p,t,o),c(t)&&i(t)&&l(t,o),0))}}));return m}})})(i,Zn),u=e=>{o.send("csp",Gt({src:e}))},g=async(e,t)=>{vt(Yn,e,Gt({set:n=>(delete Yn[e],ro(),t(n)),configurable:!0,enumerable:!1})),
oo((()=>delete Yn[e]))},p=(e,t)=>t?((e,t)=>{const n=`__p__${no()}`;(async(e,t)=>{g(e,(e=>Rt(e,t,[])))})(n,t),u('window["'+n+'"] = function(){'+e+"};"),delete Yn[n]})(e,t):u(e)})(),ro()})()};